name = "grocery-deal-checker"
main = "deal-checker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 16 * * *"]

# Replace PASTE_YOUR_KV_NAMESPACE_ID_HERE with the ID you copy from the Cloudflare dashboard
[[kv_namespaces]]
binding = "GROCERY_KV"
id = "9b65aaf687274623847a68e453cb7daa"

[vars]
VAPID_CONTACT = "mailto:natayi@gmail.com"
